language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0

env:
  global:
    - laravel='*'
    - coverage=no

matrix:
  include:
    - php: 5.5.9
      env: laravel='5.1'
    - php: 5.5.9
      env: laravel='5.2'
    - php: 5.5
      env: laravel='5.1'
    - php: 5.5
      env: laravel='5.2'
    - php: 5.6
      env: laravel='5.1'
    - php: 5.6
      env: laravel='5.2'
    - php: 5.6
      env: laravel='5.3'
    - php: 7.0
      env: laravel='5.1' coverage=yes
    - php: 7.0
      env: laravel='5.2' coverage=yes
    - php: 7.0
      env: laravel='5.3' coverage=yes
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - if [[ $laravel = '*' ]]; then travis_retry composer install --prefer-dist --no-interaction; fi
  - if [[ $laravel = '5.1' ]]; then travis_retry composer require "illuminate/contracts=5.1.*" --prefer-dist --no-interaction; fi
  - if [[ $laravel = '5.2' ]]; then travis_retry composer require "illuminate/contracts=5.2.*" --prefer-dist --no-interaction; fi
  - if [[ $laravel = '5.3' ]]; then travis_retry composer require "illuminate/contracts=5.3.*" --prefer-dist --no-interaction; fi

script:
  - if [[ $coverage = 'yes' ]]; then vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $coverage = 'no' ]]; then vendor/bin/phpunit; fi

before_install:
  - pip install --user codecov
after_success:
  - if [[ $coverage = 'yes' ]]; then codecov; fi
